### ISSUE TITLE
Отсутствует "ui" используемый в "skills/map.py"

### ISSUE THREAD

**Issue by vantu5z** [Oknolaz/vasisualy-pi#1]
Traceback (most recent call last):
  File "/home/vantu5z/git/RHVoice/vasisualy/vasisualy-pi/main.py", line 20, in <module>
    from skills import map
  File "/home/vantu5z/git/RHVoice/vasisualy/vasisualy-pi/skills/map.py", line 2, in <module>
    from ui import map
ModuleNotFoundError: No module named 'ui'

**Comment by Oknolaz** [comment]
Необходимый файл кода был добавлен в репозиторий.
